# Generated by Django 5.2 on 2025-04-05 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designbetter', '0002_alter_usuario_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='usuario_id',
            new_name='id',
        ),
    ]
