# Generated by Django 5.2 on 2025-04-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designbetter', '0004_material_patronbase_partepatron_plantillaprenda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('diseñador', 'Diseñador'), ('cliente', 'Cliente'), ('administrador', 'Administrador'), ('', '')], max_length=20),
        ),
    ]
