# Generated by Django 5.2 on 2025-05-03 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designbetter', '0005_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='DxfFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='dxf_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
