# Generated by Django 5.2 on 2025-05-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designbetter', '0006_dxffile'),
    ]

    operations = [
        migrations.AddField(
            model_name='partepatron',
            name='geometria',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
