# Generated by Django 5.2 on 2025-05-10 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designbetter', '0007_partepatron_geometria'),
    ]

    operations = [
        migrations.AddField(
            model_name='patronbase',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
