# Generated by Django 5.2 on 2025-05-26 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designbetter', '0008_patronbase_creado_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoPersonalizado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=50)),
                ('ajustes', models.TextField(blank=True)),
                ('notas', models.TextField(blank=True)),
                ('estado_pedido', models.CharField(choices=[('pendiente', 'Pendiente'), ('diseño', 'Diseño'), ('produccion', 'Producción'), ('entrega', 'Entrega'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_personalizados', to='designbetter.material')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_personalizados', to='designbetter.plantillaprenda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_personalizados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
