# Generated by Django 5.2 on 2025-07-25 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designbetter', '0009_pedidopersonalizado'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Identificador interno (p.ej. 'pendiente', 'diseño', ...).", max_length=20, unique=True)),
                ('nombre', models.CharField(help_text="Nombre legible del estado (p.ej. 'Pendiente', 'En Diseño', ...).", max_length=50)),
                ('orden', models.PositiveSmallIntegerField(help_text='Orden en que se presentan los estados (para listas y UI).')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional del estado.')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estado de Pedido',
                'verbose_name_plural': 'Estados de Pedido',
                'ordering': ['orden'],
            },
        ),
        migrations.RemoveField(
            model_name='pedidopersonalizado',
            name='estado_pedido',
        ),
        migrations.AddField(
            model_name='pedidopersonalizado',
            name='estado',
            field=models.ForeignKey(help_text='Estado actual del pedido', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='designbetter.estadopedido'),
        ),
    ]
