# Generated by Django 5.2 on 2025-07-25 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designbetter', '0010_estadopedido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidopersonalizado',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='pedidopersonalizado',
            name='material',
        ),
        migrations.RemoveField(
            model_name='pedidopersonalizado',
            name='plantilla',
        ),
        migrations.RemoveField(
            model_name='pedidopersonalizado',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='EstadoPedido',
        ),
        migrations.DeleteModel(
            name='PedidoPersonalizado',
        ),
    ]
