# Generated by Django 5.2 on 2025-09-09 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patronaje', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Identificador interno (p.ej. 'pendiente', 'diseño', ...).", max_length=20, unique=True)),
                ('nombre', models.CharField(help_text="Nombre legible del estado (p.ej. 'Pendiente', 'En Diseño', ...).", max_length=50)),
                ('orden', models.PositiveSmallIntegerField(help_text='Orden en que se presentan los estados (para listas y UI).')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional del estado.')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estado de Pedido',
                'verbose_name_plural': 'Estados de Pedido',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='PedidoPersonalizado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=50)),
                ('ajustes', models.TextField(blank=True)),
                ('notas', models.TextField(blank=True)),
                ('pago_realizado', models.BooleanField(default=False, help_text='True si el pago ya se efectuó, False en caso contrario')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('disenador', models.ForeignKey(blank=True, help_text='Diseñador asignado al pedido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_como_disenador', to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(help_text='Estado actual del pedido', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='ecommerce.estadopedido')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_personalizados', to='patronaje.plantillaprenda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_personalizados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoEstadoHistoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, help_text='Notas opcionales sobre el cambio')),
                ('estado', models.ForeignKey(help_text='Estado al que cambió el pedido', on_delete=django.db.models.deletion.PROTECT, to='ecommerce.estadopedido')),
                ('usuario', models.ForeignKey(help_text='Usuario que hizo el cambio', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historia_estados', to='ecommerce.pedidopersonalizado')),
            ],
            options={
                'verbose_name': 'Registro de Estado de Pedido',
                'verbose_name_plural': 'Historial de Estados de Pedido',
                'ordering': ['fecha'],
            },
        ),
    ]
