# Generated by Django 5.2 on 2025-07-25 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidopersonalizado',
            name='material',
        ),
    ]
