# Generated by Django 5.2 on 2025-07-25 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_remove_pedidopersonalizado_material'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoestadohistoria',
            name='disenador',
            field=models.ForeignKey(blank=True, help_text='Diseñador asignado al pedido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_como_disenador', to=settings.AUTH_USER_MODEL),
        ),
    ]
