# Generated by Django 5.2 on 2025-09-09 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DxfFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='dxf_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatronBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Código único del patrón (p.ej. PAT-TEE-BASIC)', max_length=64, null=True)),
                ('name', models.CharField(help_text='Nombre legible del patrón', max_length=150)),
                ('description', models.TextField(blank=True, default='', help_text='Descripción corta')),
                ('category', models.CharField(blank=True, default='', help_text='Categoría / familia', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', help_text='Estado de publicación', max_length=10)),
                ('params_schema', models.JSONField(blank=True, default=dict, help_text='JSON Schema de parámetros de entrada')),
                ('constraints', models.JSONField(blank=True, default=dict, help_text='Reglas/inequations/fórmulas simbólicas')),
                ('pieces', models.JSONField(blank=True, default=dict, help_text='Definición paramétrica de piezas')),
                ('grading_rules', models.JSONField(blank=True, default=dict, help_text='Reglas de tallaje/escala')),
                ('geometry_dsl', models.TextField(blank=True, help_text='(Opcional) DSL para construir el patrón 2D', null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrones_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-version'],
            },
        ),
        migrations.CreateModel(
            name='PartePatron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_parte', models.CharField(max_length=50)),
                ('medidas', models.JSONField(blank=True, null=True)),
                ('geometria', models.JSONField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('patron_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partes', to='patronaje.patronbase')),
            ],
        ),
        migrations.CreateModel(
            name='PlantillaPrenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_ropa', models.CharField(max_length=50)),
                ('tipo_cuerpo', models.CharField(max_length=50)),
                ('patron_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas', to='patronaje.patronbase')),
            ],
        ),
        migrations.CreateModel(
            name='PlantillaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas', to='patronaje.material')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='patronaje.plantillaprenda')),
            ],
        ),
        migrations.AddIndex(
            model_name='patronbase',
            index=models.Index(fields=['code'], name='idx_patron_code'),
        ),
        migrations.AddIndex(
            model_name='patronbase',
            index=models.Index(fields=['status'], name='idx_patron_status'),
        ),
        migrations.AddConstraint(
            model_name='patronbase',
            constraint=models.UniqueConstraint(fields=('code', 'version'), name='uq_patron_code_version'),
        ),
        migrations.AlterUniqueTogether(
            name='plantillamaterial',
            unique_together={('plantilla', 'material')},
        ),
    ]
