# Generated by Django 5.2 on 2025-09-06 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DxfFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='dxf_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatronBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_prenda', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=20)),
                ('tallas_disponibles', models.JSONField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('archivo_patron', models.CharField(blank=True, max_length=255)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartePatron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_parte', models.CharField(max_length=50)),
                ('medidas', models.JSONField(blank=True, null=True)),
                ('geometria', models.JSONField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('patron_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partes', to='patronaje.patronbase')),
            ],
        ),
        migrations.CreateModel(
            name='PlantillaPrenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_ropa', models.CharField(max_length=50)),
                ('tipo_cuerpo', models.CharField(max_length=50)),
                ('patron_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas', to='patronaje.patronbase')),
            ],
        ),
        migrations.CreateModel(
            name='PlantillaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas', to='patronaje.material')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='patronaje.plantillaprenda')),
            ],
            options={
                'unique_together': {('plantilla', 'material')},
            },
        ),
    ]
