# Generated by Django 5.2 on 2025-10-09 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patronaje', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='customer',
        ),
    ]
